{{- if .Values.zenNamespace}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    component: cpfs3
  name: access-to-edb-postgres
  namespace: {{.Values.zenNamespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  ingress:
  - {}
  podSelector:
    matchExpressions:
    - key: k8s.enterprisedb.io/cluster
      operator: Exists
  policyTypes:
  - Ingress
{{- end }}  
