{{- if .Values.zenNamespace}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-to-volumes
  namespace: {{.Values.zenNamespace}}
  labels:
    component: cpfs3
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
spec:
  podSelector:
    matchLabels:
      icpdsupport/app: volumes
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {} 
{{- end }}    
