apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: ibm-websphere-automation
  namespace: {{.Values.subscription.wsaOperatorNamespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetNamespaces:
  - {{.Values.subscription.wsaInstanceNamespace}}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-websphere-automation
  namespace: {{.Values.subscription.wsaOperatorNamespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  channel: {{.Values.subscription.channel}}
  installPlanApproval: {{.Values.subscription.installPlanApproval}}
  name: ibm-websphere-automation
  source: {{.Values.catalog.name}}
  sourceNamespace: openshift-marketplace