{{- if .Values.ownNamespace}}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-websphere-automation-group
  namespace: {{.Values.subscription.wsaOperatorNamespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetNamespaces:
  - {{.Values.subscription.wsaOperatorNamespace}}
---
{{- end }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-common-service-operator
  namespace: {{.Values.subscription.wsaOperatorNamespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  channel: {{.Values.subscription.channel}}
  installPlanApproval: {{.Values.subscription.installPlanApproval}}
  name: ibm-common-service-operator
  source: {{.Values.catalog.name}}
  sourceNamespace: openshift-marketplace  