{{- if .Values.commonServicesNamespace}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    component: cpfs3
  name: access-to-platform-identity-management
  namespace: {{.Values.commonServicesNamespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      k8s-app: platform-identity-management
  policyTypes:
  - Ingress
{{- end }}
