{{- if .Values.commonServicesNamespace}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-to-audit-svc
  namespace: {{.Values.commonServicesNamespace}}
  labels:
    component: cpfs3
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  podSelector:
    matchLabels:
      component: "zen-audit"
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {} 
{{- end}}