{{- if .Values.csNamespace}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-to-zen-core-api
  namespace: {{.Values.csNamespace}}
  labels:
    component: cpfs3
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
spec:
  podSelector:
    matchLabels:
      component: "zen-core-api"
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: 
        matchLabels:
          kubernetes.io/metadata.name: {{.Values.opNamespace}}
    - podSelector: {}
{{- end }}