gitops:
  namespaceScoped: true

catalog:
  name: ibm-operator-catalog
  displayName: IBM operator Catalog
  image: icr.io/cpopen/ibm-operator-catalog

subscription:
  wsaOperatorNamespace: ''
  channel: v1.8
  installPlanApproval: Automatic
  wsaInstanceNamespace: ''

operatorNamespace: ''

commonServicesNamespace: ''

licensingNamespace: ibm-licensing

certManagerNamespace: ibm-cert-manager

wsaHealth:
  spec:
    license:
      accept: ''

wsaSecure:
  spec:
    license:
      accept: ''      

wsa:
  spec:
    commonServices:
      registryNamespace: ''
    license:
      accept: ''