catalog:
  name: ibm-operator-catalog
  displayName: IBM operator Catalog
  image: icr.io/cpopen/ibm-operator-catalog:v1.31

subscription:
  wsaOperatorNamespace: openshift-operators
  channel: v1.8
  installPlanApproval: Automatic
  wsaInstanceNamespace: websphere-automation

wsaSecure:
  spec:
    license:
      accept: true

wsa:
  spec:
    license:
      accept: true

ownNamespace: false

ibmOperatorCatalog: true