catalog:
  name: ibm-operator-catalog
  displayName: IBM operator Catalog
  image: icr.io/cpopen/ibm-operator-catalog:v1.31

subscription:
  wsaOperatorNamespace: websphere-automation
  channel: v1.8
  installPlanApproval: Automatic
  wsaInstanceNamespace: websphere-automation

wsa:
  spec:
    commonServices:
      registryNamespace: websphere-automation
    license:
      accept: true

operatorNamespace: websphere-automation

commonServicesNamespace: websphere-automation

licensingNamespace: ibm-licensing

certManagerNamespace: cert-manager-operator