gitops:
  namespaceScoped: false

catalog:
  name: ibm-operator-catalog
  displayName: IBM operator Catalog
  image: icr.io/cpopen/ibm-operator-catalog

subscription:
  wsaOperatorNamespace: openshift-operators
  channel: v1.8
  installPlanApproval: Automatic
  wsaInstanceNamespace: websphere-automation

operatorNamespace: ibm-common-services

commonServicesNamespace: ibm-common-services

licensingNamespace: ibm-licensing

certManagerNamespace: ibm-cert-manager

wsaHealth:
  spec:
    license:
      accept: true

wsaSecure:
  spec:
    license:
      accept: true      

wsa:
  spec:
    license:
      accept: true