catalog:
  name: ibm-operator-catalog
  displayName: IBM operator Catalog
  image: icr.io/cpopen/ibm-operator-catalog:v1.31

subscription:
  wsaOperatorNamespace: ''
  channel: v1.8
  installPlanApproval: Automatic
  wsaInstanceNamespace: websphere-automation

wsaHealth:
  spec:
    license:
      accept: true

wsaSecure:
  spec:
    license:
      accept: true      

wsa:
  spec:
    license:
      accept: true

ownNamespace: true

ibmOperatorCatalog: true