{{- if .Values.operatorNamespace}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    component: cpfs3
  name: access-to-edb-postgres-webhooks
  namespace: {{.Values.operatorNamespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloud-native-postgresql
  policyTypes:
  - Ingress
{{- end}} 
