apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: ibm-licensing-operator-group
  namespace: {{.Values.subscription.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  targetNamespaces:
    - {{.Values.subscription.namespace}}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{.Values.subscription.name}}
  namespace: {{.Values.subscription.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  channel: {{.Values.subscription.channel}}
  source: {{.Values.catalog.name}}
  installPlanApproval: Automatic
  name: ibm-licensing-operator-app
  sourceNamespace: {{.Values.catalog.namespace}}