{{- if .Values.certManagerNamespace}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-to-cert-manager-webhook
  namespace: {{.Values.certManagerNamespace}}
  labels:
    component: cpfs3
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
spec:
  podSelector:
    matchLabels:
      app: ibm-cert-manager-webhook
  ingress:
  - {}
{{- end }}
